distro: xenial
cache: bundler
language: ruby
rvm:
  - 2.2.10
  - 2.6.6
  - 2.7.2
  - 3.0.0
before_install:
  - gem update bundler

# This prevents testing branches that are created just for PRs
branches:
  only:
  - master
